# Generated by Django 5.1.6 on 2025-02-17 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSessionManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessionUUID", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "sessionStatus",
                    models.BooleanField(
                        default=False, help_text="Current Session Status"
                    ),
                ),
                (
                    "sessionCreatedOn",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the session was created"
                    ),
                ),
                (
                    "sessionLastAccessedOn",
                    models.DateTimeField(
                        auto_now=True, help_text="Session Last Accessed On"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Chat Session Initiated by which User",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionChatInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userQuestion", models.TextField(default=None)),
                ("aiResponse", models.TextField(default=None)),
                ("generatedOn", models.DateTimeField(auto_now_add=True)),
                (
                    "chatSession",
                    models.ForeignKey(
                        help_text="Document Related to Which Session",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="qna.chatsessionmanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionDocumentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canParticipate",
                    models.BooleanField(
                        default=True,
                        help_text="Need to add this document while given answer to the user",
                    ),
                ),
                (
                    "documentAddedOn",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the document was added to the session",
                    ),
                ),
                (
                    "documentUpdatedOn",
                    models.DateTimeField(
                        auto_now=True, help_text="When the last document was updated"
                    ),
                ),
                (
                    "chatSession",
                    models.ForeignKey(
                        help_text="Document Related to Which Session",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="qna.chatsessionmanager",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document Info of the given Session",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="docops.documentinfo",
                    ),
                ),
            ],
        ),
    ]
