# Generated by Django 5.1.6 on 2025-02-15 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentUUID', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('documentTitle', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Document Uploaded Date Time')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Document Last Updated Date Time')),
                ('chunkedOn', models.DateTimeField(help_text='Document Chunked Date Time', null=True)),
                ('user', models.ForeignKey(help_text='Who uploaded this file', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('processStatus', models.ForeignKey(help_text='Current Status of Document Chunking', on_delete=django.db.models.deletion.DO_NOTHING, to='documents.processstatus')),
            ],
        ),
    ]
